// transparentImage
// moveImage
// helpImage
// checkmarkImage
// maximizeImage
// zoomOutImage
// zoomInImage
// zoomFitImage
// layersImage
// previousImage
// nextImage
// editImage
// zoomOutLargeImage
// zoomInLargeImage
// actualSizeLargeImage
// printLargeImage
// layersLargeImage
// closeLargeImage
// editLargeImage
// previousLargeImage
// nextLargeImage
// refreshLargeImage
// backLargeImage
// fullscreenLargeImage
